<!DOCTYPE html>
<html lang="en" dir="ltr">

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container" id="navbar">
                            <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header page-scroll">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-menu">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                         <!--   Modifier le nom ci-dessous (celui qui apparait en haut à gauche dans la barre de navigation)  -->

                            <a class="navbar-brand" href="#" id="brand">M2L</a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="collapse-menu">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="hidden">
                                    <a href="#mainsection"></a>
                                </li>

                              <!--  CI-DESSOUS POUR CHANGER LES RUBRIQUES :  ACCUEIL - SERVICES - CONTACT -->

                                <li class="page-scroll">
                                    <a href="#mainsection">Accueil</a>
                                </li>
                                <li class="page-scroll">
                                    <a href="#section1">Services</a>
                                </li>

                                <li class="page-scroll">
                                    <a href="#contact">Contact</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
      </div>
    </nav>
